name: Haskell CI

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-haskell@v1.1.4
      with:
        ghc-version: '9.12.2'
        cabal-version: '3.16'

    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ~/HQPlayground/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      working-directory: ./HQPlayground
      run: |
        sudo apt-get install libblas-dev liblapack-dev
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      working-directory: ./HQPlayground
      run: cabal build --enable-tests --enable-benchmarks all
    - name: Run tests
      working-directory: ./HQPlayground
      run: cabal test all
